### ISSUE TITLE
linecap Issue

### ISSUE THREAD

**Issue by Happyandhappy** [delowardev/vue3-circle-progress#1]
`<circle-progress
                  :size="16"
                  :border-bg-width="5"
                  :border-width="5"
                  :percent="40"
                  :linecap="butt"
                />`

:linecap is not working.
Can you fix it up please?

**Comment by delowardev** [comment]
Sure, I'm on it

**Comment by Happyandhappy** [comment]
Oh, sorry, it worked fine. like following.
`<circle-progress
                  :size="16"
                  :border-bg-width="5"
                  :border-width="5"
                  :percent="40"
                  linecap="butt"
                />`

**Comment by Happyandhappy** [comment]
Thank you so much
