### ISSUE TITLE
Title inside the circle

### ISSUE THREAD

**Issue by thiagocr2017** [delowardev/vue3-circle-progress#2]
Hi Delowar Hossain, tanks for this vue component, I have a question for you, how can i set title inside de circle, example 55% and will be cool if the title go 0%... to 100% if is posible.

**Comment by thiagocr2017** [comment]
i to like that:
set <text></text> svg atribute ; set props title:Boolean false its work but i think you have a better way?

**Comment by jeffery36** [comment]
Hello thiagocr2017, can you explain that how you set title inside the circle, I don't quite understand your way. If you answer me, I will be very appreciate!!!

**Comment by Armagedoomutils** [comment]
Did you manage to get a title inside the circle? I really need to be able to write text / percentage inside there, as its shown in the demo images!

**Comment by delowardev** [comment]
Hi @Armagedoomutils, I will add this feature by tomorrow.

**Comment by delowardev** [comment]
A new version has been released with this feature, here is the demo: 
https://codesandbox.io/s/determined-dawn-3ybev?file=/src/App.vue

@thiagocr2017 @Armagedoomutils

**Comment by BMikic** [comment]
hi, nice work! How I can show % after counter numbers

**Comment by BMikic** [comment]
hi, nice work! How can I show % after counter numbers

**Comment by nicoagp** [comment]
Hi, I can not make it work. I add the unit prop but it is not showing.
Is it possible to add custom text inside of the circle? I want to display Numbers, as I do have this as a progress slider, so each cirlce would be a day. Like Day 1, day 2, and so on
