### ISSUE TITLE
Vue 3 with typescript setup. No types from vue3-circle-progress

### ISSUE THREAD

**Issue by vutran6853** [delowardev/vue3-circle-progress#6]
Hello ,

I spin up a new Vue 3 project with typescript from Vue CLI command. I open up my IDE and try to import CircleProgress from vue3-circle-progress. 

I get error/warning from 

```
Try `npm i --save-dev @types/vue3-circle-progress` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue3-circle-progress';`Vetur(7016)
```

**Comment by delowardev** [comment]
Hello @vutran6853,

You can actually fix it by using the code below in any `*.d.ts` file in your project.

`declare module 'vue3-circle-progress'; `

Thanks.

**Comment by vutran6853** [comment]
Well thank for quick solution. I would think this is not good solution since your plugin should have it for us. Try to provided some feedback on your tool.

I think this issue should not be close since you see more report on this if another user are using typescript and get same error.
